apiVersion: apps/v1
kind: Deployment
metadata:
   name: laravel-deployment
   labels:
      app: laravel
spec:
   replicas: 2
   selector:
      matchLabels:
         app: laravel
   template:
      metadata:
         labels:
                 app: laravel
      spec:
             containers:
                 - name: laravel
                   image: ikhsannugs/laravel:versi
                   ports:
                     - name: http
                       containerPort: 8000
                       
